SELECT
    SOURCE_TABLE.PARTY_ID                               AS ID_TIERS,
    SOURCE_TABLE.BIRTH_DATE                             AS DATENAISSANCE,
    SOURCE_TABLE.MARITAL_STATUS                         AS STATUTMARITAL,
    SOURCE_TABLE.GENDER                                 AS GENRE,
    SOURCE_TABLE.DEATH_DATE                             AS DATADECES,
    SOURCE_TABLE.MAIDEN_NAME                            AS NOMJEUNEFILE,
    SOURCE_TABLE.BIRTH_STATE_COUNTRY                    AS DEPARTEMENTNAISSANCE,
    SOURCE_TABLE.BIRTH_COUNTRY                          AS PAYSNAISSANCE,
    SOURCE_TABLE.BIRTH_CITY                             AS VILLENAISSANCE,
    SOURCE_TABLE.BIRTH_STATE_ADMINISTRATIVE_CODE        AS INSEE,
    SOURCE_TABLE.CHILD_COUNT                            AS NOMBREENFANT,
    SOURCE_TABLE.OCCUPATION_CLASS                       AS CATEGORIEPROFESSIONNELLE,
    SOURCE_TABLE.NATIONALITY                            AS NATIONALITE,
    SOURCE_TABLE.PHYSICAL_DEFFECT                       AS HANDICAP,
    SOURCE_TABLE.EFFECTIVESTARTDATE                     AS EFFECTIVESTARTDATE,
    SOURCE_TABLE.EFFECTIVEENDDATE                       AS EFFECTIVEENDDATE,
    SYSDATE                                             AS LASTMODIFIED,
    SYSDATE                                             AS CREATEDDATE
FROM
    OWN_24456_ODS.RF_KVIC_CRE_CRE_PARTIES SOURCE_TABLE
WHERE
    NOT EXISTS (
        SELECT
            1
        FROM
            OWN_24456_ODS.DH_KSTR_PERSONNE TARGET_TABLE
        WHERE
            SOURCE_TABLE.PARTY_ID = TARGET_TABLE.ID_TIERS
            AND
            SOURCE_TABLE.LASTMODIFIED >= (
                SELECT
                    DAT_VAL
                FROM
                    parametrage
            )
            AND
            SOURCE_TABLE.BIRTH_DATE = TARGET_TABLE.DATENAISSANCE
            AND
            SOURCE_TABLE.MARITAL_STATUS = TARGET_TABLE.STATUTMARITAL
            AND
            SOURCE_TABLE.GENDER = TARGET_TABLE.GENRE
            AND
            SOURCE_TABLE.DEATH_DATE = TARGET_TABLE.DATADECES
            AND
            SOURCE_TABLE.MAIDEN_NAME = TARGET_TABLE.NOMJEUNEFILE
            AND
            SOURCE_TABLE.BIRTH_STATE_COUNTRY = TARGET_TABLE.DEPARTEMENTNAISSANCE
            AND
            SOURCE_TABLE.BIRTH_COUNTRY = TARGET_TABLE.PAYSNAISSANCE
            AND
            SOURCE_TABLE.BIRTH_CITY = TARGET_TABLE.VILLENAISSANCE
            AND
            SOURCE_TABLE.BIRTH_STATE_ADMINISTRATIVE_CODE = TARGET_TABLE.INSEE
            AND
            SOURCE_TABLE.CHILD_COUNT = TARGET_TABLE.NOMBREENFANT
            AND
            SOURCE_TABLE.OCCUPATION_CLASS = TARGET_TABLE.CATEGORIEPROFESSIONNELLE
            AND
            SOURCE_TABLE.NATIONALITY = TARGET_TABLE.NATIONALITE
            AND
            SOURCE_TABLE.PHYSICAL_DEFFECT = TARGET_TABLE.HANDICAP
    )
