SELECT
    SOURCE_TABLE.PARTY_ID                               AS 'ID_TIERS',
    SOURCE_TABLE.BIRTH_DATE                             AS 'TYPE_PARTY',
    SOURCE_TABLE.MARITAL_STATUS                         AS 'TITLE',
    SOURCE_TABLE.GENDER                                 AS 'FIRST_NAME',
    SOURCE_TABLE.DEATH_DATE                             AS 'NAME',
    SOURCE_TABLE.MAIDEN_NAME                            AS 'PARTICULE',
    SOURCE_TABLE.BIRTH_STATE_COUNTRY                    AS 'ACTIVE_STATUS',
    SOURCE_TABLE.BIRTH_CITY                             AS 'COMMERCIAL_STATUS',
    SOURCE_TABLE.BIRTH_STATE_ADMINISTRATIVE_CODE        AS 'LEGAL_ENTITY_IDENTIFIER',
    SOURCE_TABLE.CHILD_COUNT                            AS 'LEGAL_ENTITY_IDENTIFIER',
    SOURCE_TABLE.OCCUPATION_CLASS                       AS 'LEGAL_ENTITY_IDENTIFIER',
    SOURCE_TABLE.NATIONALITY                            AS 'LEGAL_ENTITY_IDENTIFIER',
    SOURCE_TABLE.PHYSICAL_DEFFECT                       AS 'LEGAL_ENTITY_IDENTIFIER',
    SOURCE_TABLE.EFFECTIVESTARTDATE                     AS 'EFFECTIVESTARTDATE',
    SOURCE_TABLE.EFFECTIVEENDDATE                       AS 'EFFECTIVEENDDATE',
    SYSDATE                                             AS 'LASTMODIFIED',
    SYSDATE                                             AS 'CREATEDDATE'
FROM
    OWN_24456_ODS.RF_KVIC_CRE_CRE_PARTIES SOURCE_TABLE
WHERE
    NOT EXISTS (
        SELECT
            1
        FROM
            OWN_24456_ODS.DH_KSTR_PERSONNE TARGET_TABLE
        WHERE
            SOURCE_TABLE.PARTY_ID = TARGET_TABLE.ID_TIERS
            AND
            SOURCE_TABLE.LASTMODIFIED >= (
                SELECT
                    DAT_VAL
                FROM
                    parametrage
            )
            AND
            SOURCE_TABLE.PARTY_ID = TARGET_TABLE.ID_TIERS
            AND
            SOURCE_TABLE.BIRTH_DATE = TARGET_TABLE.TYPE_PARTY
            AND
            SOURCE_TABLE.MARITAL_STATUS = TARGET_TABLE.TITLE
            AND
            SOURCE_TABLE.GENDER = TARGET_TABLE.FIRST_NAME
            AND
            SOURCE_TABLE.DEATH_DATE = TARGET_TABLE.NAME
            AND
            SOURCE_TABLE.MAIDEN_NAME = TARGET_TABLE.PARTICULE
            AND
            SOURCE_TABLE.BIRTH_STATE_COUNTRY = TARGET_TABLE.ACTIVE_STATUS
            AND
            SOURCE_TABLE.BIRTH_CITY = TARGET_TABLE.COMMERCIAL_STATUS
            AND
            SOURCE_TABLE.BIRTH_STATE_ADMINISTRATIVE_CODE = TARGET_TABLE.LEGAL_ENTITY_IDENTIFIER
            AND
            SOURCE_TABLE.CHILD_COUNT = TARGET_TABLE.LEGAL_ENTITY_IDENTIFIER
            AND
            SOURCE_TABLE.OCCUPATION_CLASS = TARGET_TABLE.LEGAL_ENTITY_IDENTIFIER
            AND
            SOURCE_TABLE.NATIONALITY = TARGET_TABLE.LEGAL_ENTITY_IDENTIFIER
            AND
            SOURCE_TABLE.PHYSICAL_DEFFECT = TARGET_TABLE.LEGAL_ENTITY_IDENTIFIER
    )
