SELECT
    SOURCE_TABLE.PARTY_ID                       AS 'ID_TIERS',
    SOURCE_TABLE.LEGAL_FORM                     AS 'FORME_JURIDIQUE',
    SOURCE_TABLE.LINE_OF_BUSINESS               AS 'SECTEUR_ACTIVITE',
    SOURCE_TABLE.WEB_SITE                       AS 'WEB_SITE',
    SOURCE_TABLE.SIRET_CODE                     AS 'SIRET',
    SOURCE_TABLE.BANNER                         AS 'ENSEIGNE',
    SOURCE_TABLE.PRIMARY_ACTIVITY_CODE          AS 'CODEAPRM',
    SOURCE_TABLE.PRIMARY_ACTIVITY_TEXT          AS 'LIBELLEAPRM',
    SOURCE_TABLE.BUSINESS_INFO                  AS 'BUSINESS_INFO',
    SOURCE_TABLE.FIRM_NUMBER                    AS 'IDENTIFIANTENTREPRISE',
    SOURCE_TABLE.PRIMARY_RNA_CODE               AS 'RNA_CODE',
    SOURCE_TABLE.PRIMARY_RNA_COUNTRY            AS 'PAYSENREGISTREMENT',
    SOURCE_TABLE.EFFECTIVESTARTDATE             AS 'EFFECTIVESTARTDATE',
    SOURCE_TABLE.EFFECTIVEENDDATE               AS 'EFFECTIVEENDDATE',
    SYSDATE                                     AS 'LASTMODIFIED',
    SYSDATE                                     AS 'CREATEDDATE'
FROM
    OWN_24456_ODS.RF_KVIC_CRE_CRE_ORGANIZATIONS SOURCE_TABLE
WHERE
    NOT EXISTS (
        SELECT
            1
        FROM
            OWN_24456_ODS.DH_KSTR_ORGANIZATIONS TARGET_TABLE
        WHERE
            SOURCE_TABLE.PARTY_ID = TARGET_TABLE.ID_TIERS
            AND
            SOURCE_TABLE.LASTMODIFIED >= (
                SELECT
                    DAT_VAL
                FROM
                    parametrage
            )
            AND
            SOURCE_TABLE.ID_TIERS = TARGET_TABLE.ID_TIERS
            AND
            SOURCE_TABLE.LEGAL_FORM = TARGET_TABLE.FORME_JURIDIQUE
            AND
            SOURCE_TABLE.LINE_OF_BUSINESS = TARGET_TABLE.SECTEUR_ACTIVITE
            AND
            SOURCE_TABLE.WEB_SITE = TARGET_TABLE.WEB_SITE
            AND  SECTEUR_ACTIVITE
            SOURCE_TABLE.SIRET_CODE = TARGET_TABLE.SIRET
            AND  
            SOURCE_TABLE.BANNER = TARGET_TABLE.ENSEIGNE
            AND  
            SOURCE_TABLE.PRIMARY_ACTIVITY_CODE = TARGET_TABLE.CODEAPRM
            AND  
            SOURCE_TABLE.PRIMARY_ACTIVITY_TEXT = TARGET_TABLE.LIBELLEAPRM
            AND  
            SOURCE_TABLE.BUSINESS_INFO = TARGET_TABLE.BUSINESS_INFO
            AND  
            SOURCE_TABLE.FIRM_NUMBER = TARGET_TABLE.IDENTIFIANTENTREPRISE
            AND  
            SOURCE_TABLE.PRIMARY_RNA_CODE = TARGET_TABLE.RNA_CODE
            AND  
            SOURCE_TABLE.PRIMARY_RNA_COUNTRY = TARGET_TABLE.PAYSENREGISTREMENT
    )
