MERGE
    INTO OWN_24456_ODS.DH_KSTR_ROLECONTRATPERSONNE TARGET_TABLE
USING (
        SELECT
            LEAD(EFFECTIVESTARDDATE, 1) OVER (PARTITION BY ID_SITUATION ORDER BY EFFECTIVESTARDDATE) AS DATE_SUIV,
            EFFECTIVESTARDDATE,
            EFFECTIVEENDDATE,
            ID_SITUATION
        FROM
            OWN_24456_ODS.DH_KSTR_ROLECONTRATPERSONNE
        WHERE
            EFFECTIVEENDDATE = TO_DATE('31/12/9999', 'DD/MM/YYYY')
) SOURCE_TABLE
ON (
    TARGET_TABLE.EFFECTIVESTARDDATE = SOURCE_TABLE.EFFECTIVESTARDDATE
    AND
    TARGET_TABLE.ID_SITUATION = SOURCE_TABLE.ID_SITUATION
)
WHEN MATCHED THEN UPDATE
    SET 
        TARGET_TABLE.EFFECTIVESTARDDATE = SOURCE_TABLE.DATE_SUIV,
        TARGET_TABLE.LASTMODIFIED = CURRENT_TIMESTAMP
WHERE
    SOURCE_TABLE.DATE_SUIV IS NOT NULL
    AND
    TARGET_TABLE.EFFECTIVEENDDATE != SOURCE_TABLE.DATE_SUIV
;
